Move all App contents except modals to new Layout child component
No longer need to memoize all the modals (parent component never renders), improve readability (separation of concerns)

Exception: Modals that consume state (EditModal, ChangeQrModal) still in Layout (can't lift up to App without using state there and then everything would re-render)